# Generated by Django 4.2.7 on 2024-01-11 11:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterUniqueTogether(
            name='compra',
            unique_together={('fecha', 'usuario', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('modelo', 'nombre_marca')},
        ),
    ]
